
trigger:
- main

pool: default


jobs:
- job: sonarqube

  steps:
#- script: echo Hello, world!
#  displayName: 'Run a one-line script'

  - task: SonarQubePrepare@5
  inputs:
    SonarQube: 'Sonarqube'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'demo_demo_AYd32B4Luc5_K2z0yugb'
    cliSources: '.'

  - task: SonarQubeAnalyze@5
  - task: SonarQubePublish@5
  inputs:
   pollingTimeoutSec: '300'

- job: FailInspect
  dependson: sonarqube
  condition: Failed()
  
  steps:
  script: echo TestFail!


