
trigger:
- main

pool: default

jobs:
- job: test
  steps:
  - script: echo Hi !
  - task: SonarQubePrepare@5
    inputs:
      SonarQube: 'Sonarqube'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliProjectKey: 'demo_demo_AYd4JvUAhsB8ujfIXuTl'
      cliSources: '.'
  - task: SonarQubeAnalyze@5
  
  - task: SonarQubePublish@5
    inputs:
      pollingTimeoutSec: '300'

- job: FailInspect
  dependsOn: test
  condition: Failed()
  
  steps:
  - script: echo TestFail!
    displayName: Fail

- job: Imaging

  steps:
  - task: Docker@2
    inputs:
      containerRegistry: 'docker'
      repository: 'nathivitas/demo'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'

  - task: Bash@3
    inputs:
      filePath: '$(System.DefaultWorkingDirectory)/files.sh'
    
  
  
  - task: Bash@3
    inputs:
     filePath: '$(System.DefaultWorkingDirectory)/hello.sh'