stages:
  - stage: validate
    jobs:
    - job: validate
      continueOnError: false
      steps:
      - task: TerraformInstaller@0
        inputs:
          terraformVersion: 'latest'
      - task: TerraformTaskV3@3
        inputs:
          provider: 'azurerm'
          command: 'init'
          backendServiceArm: 'ncpcaraballo1(1)(9ee63a25-6edb-46ea-a1a0-3b00fbcf7f3f)'
          backendAzureRmResourceGroupName: 'TerraformInfra'
          backendAzureRmStorageAccountName: 'natyca'
          backendAzureRmContainerName: 'natyca'
          backendAzureRmKey: 'natyca.tfstate'
      - task: TerraformTaskV3@3
        inputs:
          provider: 'azurerm'
          command: 'validate'
  - stage: deploy
    jobs:
    - deployment: Production_Deployment
      continueOnError: false
      environment: 'Production'
      strategy:
       runOnce:
        deploy:
         steps:
           - checkout: self
           - task: TerraformInstaller@0
             inputs:
               terraformVersion: 'latest'
           - task: TerraformTaskV3@3
             inputs:
               provider: 'azurerm'
               command: 'init'
               backendServiceArm: 'ncpcaraballo1(1)(9ee63a25-6edb-46ea-a1a0-3b00fbcf7f3f)'
               backendAzureRmResourceGroupName: 'TerraformInfra'
               backendAzureRmStorageAccountName: 'natyca'
               backendAzureRmContainerName: 'natyca'
               backendAzureRmKey: 'naty.tfstate'
           - task: TerraformTaskV3@3
             inputs:
               provider: 'azurerm'
               command: 'plan'
               environmentServiceNameAzureRM: 'ncpcaraballo1(1)(9ee63a25-6edb-46ea-a1a0-3b00fbcf7f3f)'

           - task: TerraformTaskV3@3
             inputs:
               provider: 'azurerm'
               command: 'apply'
               environmentServiceNameAzureRM: 'ncpcaraballo1(1)(9ee63a25-6edb-46ea-a1a0-3b00fbcf7f3f)'
 



